  #YML
name: Build and Release Debug APK

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew



      - name: Update Secrets.txt with GitHub secrets and rename to Secrets.java
        run: |
          echo "package com.example.sikarwartechservices.Constants;" > app/src/main/java/com/example/sikarwartechservices/Constants/Secrets.java
          echo "" >> app/src/main/java/com/example/sikarwartechservices/Constants/Secrets.java
          echo "public interface Secrets {" >> app/src/main/java/com/example/sikarwartechservices/Constants/Secrets.java
          echo "    String userName = \"$secrets.USERNAME\";" >> app/src/main/java/com/example/sikarwartechservices/Constants/Secrets.java
          echo "    String password = \"$secrets.PASSWORD\";" >> app/src/main/java/com/example/sikarwartechservices/Constants/Secrets.java
          echo "    String DBServerIP = \"$secrets.DBSERVERIP\";" >> app/src/main/java/com/example/sikarwartechservices/Constants/Secrets.java
          echo "    String portNo = \"$secrets.PORTNO\";" >> app/src/main/java/com/example/sikarwartechservices/Constants/Secrets.java
          echo "    String testDatabaseName = \"$secrets.TESTDATABASENAME\";" >> app/src/main/java/com/example/sikarwartechservices/Constants/Secrets.java
          echo "    String productionDatabaseName = \"$secrets.PRODUCTIONDATABASENAME\";" >> app/src/main/java/com/example/sikarwartechservices/Constants/Secrets.java
          echo "    String loginProcedureName = \"$secrets.LOGINPROCEDURENAME\";" >> app/src/main/java/com/example/sikarwartechservices/Constants/Secrets.java
          echo "}" >> app/src/main/java/com/example/sikarwartechservices/Constants/Secrets.java
          mv app/src/main/java/com/example/sikarwartechservices/Constants/Secrets.txt app/src/main/java/com/example/sikarwartechservices/Constants/Secrets.java


      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # - name: Build Release APK
      #   run: ./gradlew assembleRelease

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESSTOKEN }}
        with:
          tag_name: ${{ format('{0}-{1}', 'debug', github.run_number) }}
          release_name: Debug APK Release
          draft: false
          prerelease: false

      - name: Handle Existing Release
        id: handle_existing_release
        run: |
          if [ "${{ steps.create_release.outputs.status }}" == 'failure' ]; then
            echo "Tag name already exists. Creating a new release with an incremented tag name."
            i=1
            while true; do
              new_tag_name="${{ format('{0}-{1}', 'debug', github.run_number) }}_${i}"
              echo "Trying tag name: $new_tag_name"
              if ! git rev-parse --verify "refs/tags/$new_tag_name" >/dev/null 2>&1; then
                echo "Creating release with tag name: $new_tag_name"
                echo "::set-output name=tag_name::$new_tag_name"
                break
              fi
              i=$((i+1))
            done
          else
            echo "::set-output name=tag_name::${{ steps.create_release.outputs.tag_name }}"
          fi

      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # - name: Upload Release APK
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: release-apk
      #     path: app/build/outputs/apk/release/app-release.apk

      - name: Attach APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESSTOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive
